kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  privileged: true
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: kfechter/budgetkeeper
    tags: 
    - latest
  when:
    branch:
    - main