kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  privileged: true
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: kfechter/budgetkeeper
    tags: 
    - latest
  when:
    branch:
    - main

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: ssh_host
    username: 
      from_secret: ssh_user
    password: 
      from_secret: ssh_password
    port: 22
    command_timeout: 2m
    script:
      - bash /home/kfechter/docker.sh