// <auto-generated />
using System;
using BudgetKeeper.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetKeeper.EFCore.Migrations
{
    [DbContext(typeof(BudgetKeeperContext))]
    partial class BudgetKeeperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetKeeper.Domain.Entities.BudgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DebtAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("DebtName")
                        .HasColumnType("text");

                    b.Property<decimal?>("MonthlyPayment")
                        .HasColumnType("numeric");

                    b.Property<bool?>("PaidOff")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("BudgetItems");
                });
#pragma warning restore 612, 618
        }
    }
}
